# -*- coding: utf-8 -*-
"""problem1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gj6-iYE9v6hkUXIXsJu1D2vJhLbGbu7t
"""

def series_sum(n):
    f2 = 1 
    f1 = 1 
    sum = 0
    while True :
        f = f2 + f1 
        if f >= n: 
          return sum
        if f % 2 == 0: 
          sum += f
        f2= f1 
        f1 = f

series_sum(4000000) #Since numbers in series should be less than 4 million